<a href="https://colab.research.google.com/github/brunogds/ED/blob/master/Aula_2503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Manipulando Matrizes**

In [ ]:
# o resultado não é o esperado
A = [[1,2,3], [4,5,6], [7,8,9]] 
B = [[1,-1,0], [0,1,2], [1,1,1]]

# não funciona como o desejado
# não soma as matrizes, concatena!
C = A + B 

print(C)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, -1, 0], [0, 1, 2], [1, 1, 1]]


# **A Biblioteca NumPy**

O NumPy é uma biblioteca da linguagem Python com funções que permitem trabalhar com vetores e matrizes de forma simplificada. Provê diversas funções e operações sofisticadas. A biblioteca é implementada em linguagem C, o que dá uma grande velocidade às operações realizadas.

In [ ]:
# importando a biblioteca e dando um apelido (np)
import numpy as np 

A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[1,-1,0], [0,1,2], [1,1,1]])

C = A + B 

print("O resultado é:")
print(C)

O resultado é:
[[ 2  1  3]
 [ 4  6  8]
 [ 8  9 10]]


In [ ]:
# resolvendo sistemas lineares
#              x  y  z   x  y  z   x  y  z
A = np.array([[1, 1, 1],[1, 1, 2],[2, 3, 5]])
B = np.array([1000, 2000, 2500])

# Resolver o sistema linear? AX = B (equação matricial)
# X = [x, y, z]
X = np.linalg.solve(A,B)  

print("A solução é:", X, "FIM")

A solução é: [ 2500. -2500.  1000.] FIM


In [ ]:
A = np.array([[1, 1, 1],[1, 1, 2],[2, 3, 5]])
B = np.array([1000, 2000, 2500])

X = np.linalg.solve(A,B)  

print("A solução é:", X, "FIM")

A solução é: [ 2500. -2500.  1000.] FIM


In [ ]:
A = np.array([[1, 1, 1],[1, 1, 2],[2, 3, 5]])

v = np.linalg.det(A)
print(v)

-1.0


In [ ]:
A = np.array([[1, 1, 1],[1, 1, 2],[2, 3, 5]])

transpostaA = np.transpose(A)

print("Matriz A:")
print(A)

print("Transposta de A:")
print(transpostaA)

Matriz A:
[[1 1 1]
 [1 1 2]
 [2 3 5]]
Transposta de A:
[[1 1 2]
 [1 1 3]
 [1 2 5]]


In [ ]:
A = np.array([[1/2,2/3,0.75], [4,5,6], [7,8,9]])
B = np.array([[1,-1,0], [0,1,2], [1,1,1]])

# cuidado!
C = A * B
print("Não é multiplicação matricial, é multiplicação elemento a elemento:")
print(C)

# multiplicação matricial
print("É multiplicação matricial:")
C = np.matmul(A,B)
print(C)

Não é multiplicação matricial, é multiplicação elemento a elemento:
[[ 0.5        -0.66666667  0.        ]
 [ 0.          5.         12.        ]
 [ 7.          8.          9.        ]]
É multiplicação matricial:
[[ 1.25        0.91666667  2.08333333]
 [10.          7.         16.        ]
 [16.         10.         25.        ]]


# **Comando Repetitivo: for**

In [ ]:
print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)
print(11)
# e se eu precisar imprimir até 1000 ?
# 1000 linhas ??? Teria que digitar tudo?
# como melhorar?

1
2
3
4
5
6
7
8
9
10
11


In [ ]:
# comando repetitivo: for
# i é variável que controla o for (início e fim)
fim = int(input("Qual o limite do for? "))
for i in range(1,fim+1):  # para o i variando de =1 até <10 (1, 2, 3, 4, 5, 6, 7, 8, 9), repete 9 vezes
  print(i)   # é o comando que será repetido  (cuidado com a identação, espaço no começo)
print("fim")


Qual o limite do for? 5
1
2
3
4
5
fim


In [ ]:
for i in range(1,12):
  print(i)
print("FIM")

1
2
3
4
5
6
7
8
9
10
11
FIM


# **Exercício 1.1.11 da Lista**

In [ ]:
import numpy as np

# definir a matriz A
A = np.array([[1, 1/2], [0, 1/3]])

# calcular A¹, A², A³ ...
A1 = A                      # inicial
A2 = np.matmul(A1, A)       # A² = A¹.A   
A3 = np.matmul(A2, A)       # A³ = A².A
A4 = np.matmul(A3, A)       # A⁴ = A³.A 
A5 = np.matmul(A4, A)       # A⁵ = A⁴.A 
A6 = np.matmul(A5, A)       # A⁶ = A⁵.A  
print(A6)

[[1.         0.74897119]
 [0.         0.00137174]]


In [ ]:
import numpy as np

# definir a matriz A
A = np.array([[1, 1/2], [0, 1/3]])

# conheço A¹
Ak = A       # inicial k = 1 

# calcular A², A³ ..., A⁹ 
# k é a variável que controla a repetição
for k in range(2, 5):
  # novo Ak = Ak antigo vezes A
  #    A^k = A^(k-1) * A
  #    A^(k-1) é a potência anterior 
  #    A^k é a nova potência 
  # primeira vez no for k = 2   Ak = Ak * A    A² = A¹. A
  Ak = np.matmul(Ak, A)   
  # \n pula linha
  # k tem que ser fora das aspas
  print("\n",k,"a. Potência: ")
  print(Ak)                   


 2 a. Potência: 
[[1.         0.66666667]
 [0.         0.11111111]]

 3 a. Potência: 
[[1.         0.72222222]
 [0.         0.03703704]]

 4 a. Potência: 
[[1.         0.74074074]
 [0.         0.01234568]]


In [ ]:
import numpy as np

A = np.array([[1, 1/2], [0, 1/3]])

Ak = A       

for k in range(2, 5):
  Ak = np.matmul(Ak, A)   
  print("\n",k,"a. Potência: ")
  print(Ak)  


 2 a. Potência: 
[[1.         0.66666667]
 [0.         0.11111111]]

 3 a. Potência: 
[[1.         0.72222222]
 [0.         0.03703704]]

 4 a. Potência: 
[[1.         0.74074074]
 [0.         0.01234568]]


In [ ]:
import numpy as np

# definir a matriz A
A = np.array([[1, 1/2], [0, 1/3]])

# conheço A¹
matriz = A       # inicial k = 1 

# calcular A², A³ ..., A⁹ 
# k é a variável que controla a repetição
p = int(input("Qual potência? "))

for k in range(2, p+1):
  matriz = np.matmul(matriz, A)   # matriz = matriz.A
  print("\n",k,"a. Potência: ")
  print(matriz)  

Qual potência? 7

 2 a. Potência: 
[[1.         0.66666667]
 [0.         0.11111111]]

 3 a. Potência: 
[[1.         0.72222222]
 [0.         0.03703704]]

 4 a. Potência: 
[[1.         0.74074074]
 [0.         0.01234568]]

 5 a. Potência: 
[[1.         0.74691358]
 [0.         0.00411523]]

 6 a. Potência: 
[[1.         0.74897119]
 [0.         0.00137174]]

 7 a. Potência: 
[[1.00000000e+00 7.49657064e-01]
 [0.00000000e+00 4.57247371e-04]]


In [ ]:
import numpy as np

A = np.array([[0,0,1], [1,0,1], [0,1,0]])
B = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])

ordem = len(A)

print(ordem, "\n")

I = np.eye(ordem)

print(I)

# print("\n")

# print("B é diferente de I ?")
# print(A != I)
# print("\n")
# print("Algum diferente? ", (B != I).any())  # algum elemento de B é diferente de I ?

# print("\n")

# print("B é igual a I ? ")
# print(B == I)
# print("\n")
# print("Algum igual? ", (B == I).all())  # algum elemento de B é igual de I ?

3 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np

A = np.array([[0,0,1,1], [1,0,0,1], [0,1,0,1], [1,1,1,1]])
B = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])

ordem = len(A)
I = np.eye(ordem)

print("B é diferente de I ?")
print(B != I)
print("\n")
print("Algum diferente? ", (B != I).any())  # algum elemento de B é diferente de I ?


B é diferente de I ?
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]


Algum diferente?  False


In [ ]:
# i controla o for
# i começa em 1
# i vai (de 1 em 1) até < 7
for i in range(1, 7):
  print(i)

1
2
3
4
5
6


In [ ]:
i = 1  # inicio 
while (i < 7):  # fim
  print(i)
  i = i + 1     # de 1 em 1

1
2
3
4
5
6


In [ ]:
resposta = "s"  # inicio 
while resposta == "s":  # condição de parada ou condição para continuar
  print("olá")
  resposta = input("Digite s ou n: ")   # atualiza resposta para nova repetição
  

olá
Digite s ou n: s
olá
Digite s ou n: s
olá
Digite s ou n: s
olá
Digite s ou n: s
olá
Digite s ou n: n


# **Exercício 1.1.12 da Lista**

In [ ]:
import numpy as np

A = np.array([[0,0,1],[1,0,0],[0,1,0]])  # matriz do enunciado

tamanho = len(A)      # obtém a dimensão da matriz A (número de linhas)
 
I = np.eye(tamanho)   # cria uma matriz identidade com mesma dimensão da matriz A

# pensa em Ak como uma "caixinha" que você guarda coisas 
# e que vai mudando o que coloca dentro dela a cada repetição do while
Ak = A    # Ak inicia com A¹ 
k = 1     # apenas para controlar o índice da atual potência

while ((Ak != I).any()):  # enquanto for verdade que Ak não é igual à matriz I, repita:
  # o while repete os cálculos até que a condição se torne FALSA
  Ak = np.matmul(Ak, A)   # Ak (novo conteúdo da "caixinha") = Ak (conteúdo atual) * A
  k = k + 1               # próxima potência
  print("\n",k,"a. Potencia: ")   # \n pula linha, só pra deixar bonitinho na tela
  print(Ak) 
 