<a href="https://colab.research.google.com/github/brunogds/ED/blob/master/CalcDetBruno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import fractions as fr

matriz = np.array([[0,0,0],[0,0,0],[0,0,0]])
for l in range (0, 3):
  for c in range (0, 3):
    matriz[l][c] = int (input(f'Digite o valor para [{l+1},{c+1}]: '))
    print('-=' * 151
          )

det = np.linalg.det(matriz)
if det == 0:
  print('\n A não tem inversa')
else:
  inv = np.linalg.inv(matriz)
  print('\n inv =\n', inv)
  print()
  for linha in inv:
    for x in linha:
      print(fr.Fraction.from_float(x).limit_denominator(100), end='      ')
    print()

    


Digite o valor para [1,1]: 1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [1,2]: 1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [1,3]: 1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [2,1]: 2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [2,2]: 1
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [2,3]: 4
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [3,1]: 2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [3,2]: 3
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Digite o valor para [3,3]: 5
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

 inv =
 [[ 1.4  0.4 -0.6]
 [ 0.4 -0.6  0.4]
 [-0.8  0.2  0.2]]

7/5      2/5      -3/5      
2/5      -3/5      2/5      
-4/5      1/5      1/5      
