<a href="https://colab.research.google.com/github/brunogds/ED/blob/master/Simulado18.03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import fractions

print("Questão 1 \n")
A = np.array([[1,1,1],[2,1,4],[2,3,5]])

determinante = np.linalg.det(A)
if np.linalg.det(A) == 0:
    print("\na) A não tem inversa")
    print("\nb) det(A) = 0")
else:
    Inv = np.linalg.inv(A)
    print("\na) InvA =\n",Inv)
    print()
    print("InvA =")
    for linha in Inv:
        for x in linha:
            print(fractions.Fraction.from_float(x).limit_denominator(100), end="   ")
        print()
    print("\nb) det(A) =",fractions.Fraction.from_float(determinante).limit_denominator(100))

Questão 1 


a) InvA =
 [[ 1.4  0.4 -0.6]
 [ 0.4 -0.6  0.4]
 [-0.8  0.2  0.2]]

InvA =
7/5   2/5   -3/5   
2/5   -3/5   2/5   
-4/5   1/5   1/5   

b) det(A) = -5


In [ ]:
print("Questão 2 \n")
A = np.array([[1,-2,3],[-1,3,0],[2,-5,5]])
B = np.array([9, -4, 17])

if np.linalg.det(A) != 0:
    Inv = np.linalg.inv(A)
    X = np.matmul(Inv,B)
    print("Solução única:", X)

Questão 2 

Solução única: [ 1. -1.  2.]
