<a href="https://colab.research.google.com/github/brunogds/ED/blob/master/Ex%201.1.11/12(Bruno).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercício 1.1.11

In [8]:
import numpy as np

A = np.array([[1, 1/2], [0, 1/3]])
Aresult = A

p = int (input('Quantas potências deseja calcular?'))

k = 1
while k <= p:
  print(k,'ª potência:\n')
  print(Aresult)
  Aresult = np.matmul(A, Aresult)
  k += 1
  print('=-' * 15 ,'\n')


Quantas potências deseja calcular?3
1 ª potência:

[[1.         0.5       ]
 [0.         0.33333333]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- 

2 ª potência:

[[1.         0.66666667]
 [0.         0.11111111]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- 

3 ª potência:

[[1.         0.72222222]
 [0.         0.03703704]]
=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- 



Exercicio 1.1.12

In [41]:
import numpy as np

Aa = np.array([[0,0,1], [1,0,0], [0,1,0]])
A = Aa
Ab = np.array([[0,1,0,0], [-1,0,0,0], [0,0,0,1], [0,0,1,0]])
B = Ab

Ia = np.eye(len(Aa))
Ib = np.eye(len(Ab))

#Resulução item A e B
k = 1
while (Ab != Ib).any():
  print(k, 'ª potencia\n', Ab,'\n')
  Ab = np.matmul(Ab, B)
  k+=1
else:
  print('\nA^k é igual a I na', k,'ª potência', Ab)



1 ª potencia
 [[ 0  1  0  0]
 [-1  0  0  0]
 [ 0  0  0  1]
 [ 0  0  1  0]]
2 ª potencia
 [[-1  0  0  0]
 [ 0 -1  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]
3 ª potencia
 [[ 0 -1  0  0]
 [ 1  0  0  0]
 [ 0  0  0  1]
 [ 0  0  1  0]]

A^k é igual a I na 4 ª potência [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [45]:
#Resolução item C
Ac = np.array([[0,1,0,0], [0,0,1,0], [0,0,0,1],[0,0,0,0]])
C= Ac
#Nula = np.array([[0,0,0,0], [0,0,0,0], [0,0,0,0], [0,0,0,0]])
Nula = np.zeros((len(Ac), len(Ac)))
k = 1
while (Ac != Nula).any():
  print(k,'ª potencia \n', Ac, '\n')
  Ac = np.matmul(Ac, C)
  k+=1
else:
  print('A elevado a k é igual a 0 na', k,'ª potência\n', Ac)

1 ª potencia 
 [[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]] 

2 ª potencia 
 [[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]] 

3 ª potencia 
 [[0 0 0 1]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] 

A elevado a k é igual a 0 na 4 ª potência
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
